### ISSUE TITLE
Suitable 

### ISSUE THREAD

**Issue by toby-senpai** [LindseyBot/bot#1]
So she keeps saying "nothing suitable found" when I try searching r34? Is there something I need to fix in settings or is it something else?

**Comment by Fabricio20** [comment]
Hello, are you using Slash Commands or Prefix commands? (`/nsfw rule34` vs `L!rule34`)

I just did a simple test using the slash command variant and everything seems to work normally, alternatively can I know which tags you are searching for in case you are using the slash command variant?

**Comment by toby-senpai** [comment]
I was using prefix! But I'll use slash commands instead, thanks!

**Comment by toby-senpai** [comment]
Okay so I tried the slash commands and I'm still having the same problem :(

**Comment by Fabricio20** [comment]
Hello again, I'm still unable to reproduce the issue, which tags are you using? Does it work when you don't provide any tags?

**Comment by Fabricio20** [comment]
Hello, the update that has just been deployed should fix this issue, let me know if it's still happening.
